#!/bin/bash
#Install and configure adb in one step.

android_dl="http://dl.google.com/android/android-sdk_r18-linux.tgz"
android_tar="android-sdk_r18-linux.tgz"
bash_profile="$HOME/.bashrc"
sdk_path="$HOME/.sdk/android-sdk/tools"

function do_sdk(){
echo "Downloading and installing Android-SDK..."
wget $android_dl &>> /dev/null
tar xvf $android_tar &>> /dev/null

mkdir $HOME/.sdk
mv android-sdk-linux/ $HOME/.sdk/android-sdk/

echo "Creating paths in $bash_profile"
echo "
#Android Paths
export PATH="$HOME/.sdk/android-sdk/tools/:$HOME/.sdk/android-sdk/platform-tools/:${PATH}"

#Adb Alias
alias start-adb='sudo $HOME/.sdk/android-sdk/platform-tools/./adb start-server'
alias kill-adb='sudo $HOME/.sdk/android-sdk/platform-tools/./adb kill-server'
" >> $bash_profile

rm $android_tar
}

function echo_it() {
echo '
Your sdk installation is now complete!
If you could please log out or type < source ~/.bashrc > so that your new config will be laoded into memory I would appreciated it."
When you get back type < android > install the platform tools after platform tools are installed:"
Then adb should be installed!'
}

do_sdk

if [ "$?" = "0" ]; then
	echo_it
fi

exit
