#!/bin/bash
#Install and configure adb in one step.

android_dl="http://dl.google.com/android/android-sdk_r20-linux.tgz"
android_tar="android-sdk_r20-linux.tgz"
bash_profile="$HOME/.bashrc"
sdk_path="$HOME/.sdk/android-sdk/tools"

function do_sdk(){
echo "Downloading and installing Android-SDK..."
wget $android_dl &>> /dev/null
tar xvf $android_tar &>> /dev/null

mkdir $HOME/.sdk
mv android-sdk-linux/ $HOME/.sdk/android-sdk/

echo "
#Adb Alias
alias adb=\"$HOME/.sdk/android-sdk/platform-tools/./adb\"
alias fastboot=\"sudo $HOME/.sdk/android-sdk/platform-tools/./fastboot\"
alias android=\"sudo $HOME/.sdk/android-sdk/tools/./android\"
" >> $bash_profile

rm $android_tar
}

function echo_it() {
echo '
Your sdk installation is now complete!
If you could please log out or type < source ~/.bashrc > so that your new config will be laoded into memory I would appreciated it."
When you get back type < android > install the platform tools after platform tools are installed:"
Then adb should be installed!'
}

do_sdk

if [ "$?" = "0" ]; then
	echo_it
fi

exit
