#!/bin/bash
#!/bin/bash
# Written by Jeremie Long

function display_dual_monitors_no_lvds(){
xrandr --output $1 --off 
xrandr --output $2 --auto --output $3 --auto
xrandr --output $2 --right-of $3
}

function display_dual_monitors_lvds(){
xrandr --output $1 --auto --output $2 --auto
xrandr --output $1 --right-of $2
}

function display_monitor_lvds(){
xrandr --output $1 --auto
}


LIST=$(xrandr |grep -v "^ " |awk '{ print $1 }')
W_LVDS=0
for x in $LIST; do
	CHK=$(xrandr |grep $x |grep ' connected')
	if [ "$CHK" ]; then
		DISPLAYS[$W_LVDS]="$x"
		let W_LVDS=W_LVDS+1
	fi
done

N_LVDS=0
for x in $LIST; do
	if [ ! `echo $x |grep -i "lvds"` ]; then
		CHK=$(xrandr |grep $x |grep " connected")
        	if [ "$CHK" ]; then
        		let N_LVDS=N_LVDS+1
		fi
	fi
done

if [ $W_LVDS -gt $N_LVDS ]; then
	if [ $W_LVDS > 2 ]; then
		display_dual_monitors_no_lvds "${DISPLAYS[@]}"
	else
		display_dual_monitors_lvds "${DISPLAYS[@]}"
	fi
elif [ $W_LVDS -eq 1 ]; then
	display_monitor_lvds "${DISPLAYS[@]}"
fi
