#!/bin/bash
# Written by lithid

DE="Openbox"
FOLDER="$HOME/Pictures/InterfaceLift"
TMP_FILE="/tmp/index.html"
URL="http://interfacelift.com/wallpaper/downloads/date/widescreen/1680x1050/"
AGENT="Mozilla/5.0 (Windows; U; Windows NT 6.1; en-US; rv:1.9.2.3) Gecko/20100401 Firefox/3.6.3 (.NET CLR 3.5.30729)"

function OB_CMD_FUN() {
if [ -f $FOLDER/$NAME ]; then
        cp $FOLDER/$NAME ~/.wallpaper.jpg
else
        echo "$FOLDER/$NAME doesn't exist"
fi

if [ -f ~/.wallpaper.jpg ]; then
        feh --bg-scale ~/.wallpaper.jpg
else
        echo "~/.wallpaper.jpg doesn't exit"
fi
}

CHECK="1"
if [ ! -d $FOLDER ]; then
	mkdir -p $FOLDER
fi

COUNT=$(ls $FOLDER |wc -l)
if [ "$COUNT" -gt "7" ]; then
	FILE=$(ls -tr $FOLDER |head -n1)
	rm -rf $FOLDER/$FILE
fi

wget -P /tmp -nc -U "$AGENT" $URL &>> /dev/null

WALLPAPER=$(grep "/img_NEW/button_download.png" $TMP_FILE |head -n1 |cut -d\" -f2)
NAME=$(echo $WALLPAPER |cut -d/ -f4)
GNAME=$(ls $FOLDER |grep $NAME |wc -l)
if [ "$GNAME" = "1" ]; then
	CHECK="0"
fi

if [ "$CHECK" = "1" ]; then
	wget -P $FOLDER -nc -U "$AGENT" http://interfacelift.com/$WALLPAPER &>> /dev/null
	if [ "$DE" = "Gnome" ]; then
		gsettings set org.gnome.desktop.background picture-uri file://$FOLDER/$NAME
	elif [ "$DE" = "Openbox" ]; then
		OB_CMD_FUN
	else
		echo "No DE specified"
		echo "Your wallpaper is located $FOLDER/$NAME"
	fi
elif [ "$CHECK" = "0" ]; then
	echo "Nothing to do"
else
	echo "$CHECK needs to be 0 or 1, please try again."
fi

if [ -f $TMP_FILE ]; then
	rm $TMP_FILE
fi

exit 0
