#!/bin/bash
# Script for dual monitors on openbox
# Written by Jeremie Long

LVDS="LVDS1"
VGA="VGA1"
HDMI="HDMI1"

CHK_VGA=$(xrandr |grep $VGA | awk ' { print $2 } ')
CHK_HDMI=$(xrandr |grep $HDMI | awk ' { print $2 } ')

CHK_VGA_G=$(xrandr |grep $VGA | grep "+")
CHK_HDMI_G=$(xrandr |grep $HDMI | grep "+")

function dual_it_up(){
xrandr --output $LVDS --off --output $VGA --auto --output $HDMI --auto
xrandr --output $VGA --right-of $HDMI
}

if [ "$CHK_VGA" == "connected" ] || [ "$CHK_HDMI" == "connected" ]; then
	dual_it_up
elif [ "$CHK_VGA_G" ] || [ "$CHK_HDMI_G" ]; then
	dual_it_up
else
	xrandr --output $LVDS --auto
fi

exit
